listen_address = "127.0.0.1"
listen_port = 3030
# maximum requests to public endpoints (like login) per n seconds
# default: 3 requests per 10 seconds
public_routes_rate_limit = 3
public_routes_rate_limit_time_frame = 10
# maximum requests to private endpoints (those which requre authentication) per minute
# default: 25 requests per 5 seconds
private_routes_rate_limit = 25
private_routes_rate_limit_time_frame = 5

[world]
# how long should mcmanager wait for the server to gracefully shut down before killing it
stop_timeout = 15
# in what range should ports be assigned to servers
port_range = "25000-26000"

[user_defaults]
# total RAM limit (in MiB)
memory_limit = 4096
# Per-world player limit
player_limit = 10
# total wolds the user can have enabled
world_limit = 10
# amount of worlds that user can have enabled at a time
active_world_limit = 3
# total amount of storage avaliable to the user (in MiB)
storage_limit = 10240


[world_defaults]
# Default amount of memory allocated to a server (in MiB)
allocated_memory = 1024