# address of the api server
listen_address = "0.0.0.0:3030"
# maximum requests to public endpoints (like login) per n seconds
# default: 10 requests per 5 seconds
public_routes_rate_limit = [10, 5]
# maximum requests to private endpoints (those which requre authentication) per minute
# default: 50 requests per 5 seconds
private_routes_rate_limit = [50, 5]
# whether to require an invite for a user to register
require_invite_to_register = true

# how to launch and manage minecraft servers. avaliable: internal, remote, kubernetes (not implemented). this should always be "internal" for minimanager
minecraft_server_type = "internal"

# Info sent to the frontend.
[info]
name = "MCManager"
# The message displayed to users that are signing up or registering. if this is empty a message will not be displayed
login_message = ""
# the title of the login message
login_message_title = "Message"
# info, warning or none. impacts the way the message is displayed (none is the same as info but without the info icon)
login_message_type = "info"

[database]
# database: sqlite or postgres
database_type = "sqlite"
# max concurrent connections
max_connections = 5
# how long to cache users, groups and sessions (in seconds)
cache_time_to_live = 30
# PostgreSQL database host. includes username, password, hostname, port and database name
pg_host = "postgres://mcmanager:PASSWORD@localhost:5432/mcmanager"

# remote minecraft server configuration
[remote] # run the servers on a separate system using minimanager
host = "http://localhost:3031"

[velocity]
# on which port the velocity proxy should run. it should usually be the default minecraft port so 25565
port = 25565
# what is the velocity executable called. it should be placed in the data/velocity directory. for now you will have download it yourself.
executable_name = "velocity.jar"
hostname = "example.net" # under what domain is the server running on. the servers will be avaliable at server_name.example.net

[world]
# how long should mcmanager wait for the server to gracefully shut down before killing it
stop_timeout = 15
# in what range should ports be assigned to servers. it can overlap with the velocity port as this one will be skipped
port_range = [24000, 25000]
# what command should be used to launch the minecraft server.
# you can also use this to run the servers in something like firejail
# to somewhat improve the security of local servers.
java_launch_command = "java -jar -Xms512m %max_mem% %jar% -nogui"

[user_defaults]
#default user group
group_id = "AAAAAAAA" # this gets replaced with the actual id during the first setup

[world_defaults]
# Default amount of memory allocated to a server (in MiB)
allocated_memory = 1024
