[package]
name = "mcmanager"
version = "0.1.0"
edition = "2024"


#[lib]
#proc-macro = true

[dependencies]
anyhow = "1.0.97"
argon2 = "0.5.3"
chrono = "0.4.40"
rand = "0.9.0"
rusqlite = { version = "0.34.0", features = ["bundled", "chrono"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
serde_with = { version =  "3.12.0", features = ["chrono"] }
tokio = { version = "1.44.1", features = ["rt", "rt-multi-thread", "macros"] }
warp = "0.3.7"
log = "0.4.26"
warp-sessions = "1.0.19"
config = "0.15.11"
once_cell = "1.21.0"
