apiVersion: v1
kind: Pod
metadata:
  name: velocity
spec:
  containers:
    - name: velocity
      image: amazoncorretto:21
      command: ["java", "-jar", "/mnt/velocity.jar"]
      volumeMounts:
        - name: velocity-vol
          mountPath: /mnt/
  volumes:
    - name: velocity-vol
      hostPath:
          path: /home/mhanak/Code/rust/mcmanager/target/debug/data/velocity # directory location on host
          type: Directory # this field is optional
